# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chasis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chasis', models.CharField(max_length=100)),
                ('with_or_without_bay', models.CharField(choices=[('', '----Select Option----'), ('No', 'Without Bay'), ('Two', 'With Two HDD Bay'), ('Four', 'With Four HDD Bay'), ('Six', 'With Six HDD Bay')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50)),
                ('client_address', models.CharField(max_length=255)),
                ('client_address_short', models.CharField(max_length=20)),
                ('client_nick_name', models.SlugField(max_length=100)),
            ],
            options={
                'ordering': ['client', 'client_address'],
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(max_length=100)),
                ('memory', models.CharField(max_length=100)),
                ('hard_drive', models.CharField(max_length=100)),
                ('smps', models.CharField(max_length=100)),
                ('dvd_drive', models.CharField(max_length=100)),
                ('operating_system', models.CharField(max_length=100)),
                ('inclusive_part', models.CharField(max_length=200)),
                ('created', models.DateField(verbose_name='created')),
                ('save_as', models.CharField(max_length=50, unique=True)),
                ('chasis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='yapp.Chasis')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='yapp.Client')),
            ],
            options={
                'ordering': ['client', 'chasis', 'motherboard_part_no', 'processor', 'memory', 'hard_drive', 'smps', 'operating_system', 'inclusive_part', 'created', 'save_as'],
                'verbose_name': 'configuration',
                'verbose_name_plural': 'configurations',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chasis', models.CharField(blank=True, max_length=20)),
                ('motherboard', models.CharField(blank=True, max_length=20)),
                ('memory', models.CharField(blank=True, max_length=200)),
                ('hard_drive', models.CharField(blank=True, max_length=200)),
                ('smps', models.CharField(blank=True, max_length=50)),
                ('dvd_drive', models.CharField(blank=True, max_length=40)),
                ('product_key', models.CharField(blank=True, max_length=100)),
                ('extra', models.CharField(blank=True, max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('assembled_on', models.DateField(verbose_name='date')),
                ('assembled_by', models.CharField(choices=[('', '----Select a person----'), ('Luke', 'Luke Marak'), ('Balaji', 'Balaji'), ('Gopala', 'Gopalakhrishnan'), ('Mukesh', 'Mukesh Gautam'), ('Venkey', 'R.Venkatesh'), ('Manikndn', 'Manikandan'), ('Santosh', 'Santosh'), ('Others', 'Someone')], max_length=20)),
                ('save_as', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='yapp.Configuration')),
            ],
            options={
                'verbose_name': 'detail',
                'verbose_name_plural': 'details',
            },
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motherboard_part_no', models.CharField(max_length=50)),
                ('supported_processor', models.CharField(max_length=200)),
                ('number_of_mem_slot', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['motherboard_part_no', 'supported_processor', 'number_of_mem_slot'],
            },
        ),
        migrations.AddField(
            model_name='configuration',
            name='motherboard_part_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='yapp.Motherboard'),
        ),
        migrations.AlterUniqueTogether(
            name='detail',
            unique_together=set([('chasis', 'motherboard', 'memory', 'hard_drive', 'smps', 'dvd_drive', 'product_key')]),
        ),
    ]
